{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mqtt-broker
spec:
  type: ClusterIP
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}