apiVersion: v2
name: dsp-basyx
description: A Helm chart for the BasyxStarterApplication Spring Boot app
type: application
version: 0.1.0
appVersion: "0.0.1"

dependencies:
  - name: basyxstarterapplication
    version: 0.1.0
    repository: file://basyxstarterapplication
    condition: basyxstarterapplication.enabled
  - name: keycloak
    version: 24.7.4
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 12.1.31
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql-controlplane
    version: "14.0.5"
    repository: "https://charts.bitnami.com/bitnami"
    alias: postgresql-controlplane
  - name: tractusx-connector
    version: "3.0.2"
    repository: "https://eclipse-tractusx.github.io/charts/dev"
    alias: consumer-controlplane