{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.fullnameOverride }}-realm
data:
  BaSyx-realm.json: |-
{{ .Files.Get "files/BaSyx-realm.json" | indent 4 }}
{{ end -}}