apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "basyxstarterapplication.fullname" . }}-rules
  labels:
    {{- include "basyxstarterapplication.labels" . | nindent 4 }}
data:
  rules.json: |-
{{ .Files.Get "files/rules.json" | indent 4 }}